#!/usr/bin/env python3
"""
Self-Sustaining Computation

Every computational architecture has a frozen level — a level where
structure is GIVEN, never GENERATED by the system itself:

  Transformers: weights are frozen during inference.
  SSMs: state dynamics are parameterized, never self-produced.
  Gradient descent: the loss function never changes.

A living system has no frozen level. Its structure is continuously
produced by the very processes that the structure enables.

This is not a metaphor. It is a mathematical condition:

  SELF-REFERENCE: The state determines the dynamics.
  SUSTAINED DISEQUILIBRIUM: The system never reaches equilibrium.
  TRAJECTORY AS COMPUTATION: The attractor basin IS the output.

The mathematical realization:

  State: x ∈ ℝ^d, arranged as a circular lattice.

  Self-referential map:
    Φ(x)_k = tanh(α·x_k + β·x_{k+1}·x_{k-1})

  Two terms only:
    α·x_k          — self-drive (α > 1 → zero is unstable)
    β·x_{k+1}·x_{k-1} — cross-dimensional coupling
                        (neighbors multiply to gate each dimension)

  The state determines the dynamics (through β·x_{k+1}·x_{k-1}).
  The dynamics determine the next state.
  The loop closes. There is no external program.

  Multi-cell coupling:
    x'_{i,k} = Φ(x_i)_k + ε · Σ_j a_ij · (Φ_i(x_j)_k − Φ(x_i)_k)

  Where:
    Φ_i(y)_k = tanh(α·y_k + β·x_{i,k+1}·y_{k-1})
    (cell i applies its own structure to neighbor j's state)

    a_ij = exp(x_i·x_j / (d·τ)) / Z_i
    (coupling strength = state similarity, self-organized topology)

  A cell near a fixed point of its own Φ resists coupling (autonomy).
  A cell far from any fixed point is shaped by neighbors (plasticity).
  This isn't designed. It falls out of the dynamics.

  Computation: different inputs → different attractor basins → different outputs.
  Adaptation: past inputs reshape the attractor landscape.
  Homeostasis: perturbation followed by return to the active trajectory.

  No loss function. No optimizer. No training/inference split.
  No dependencies. Pure Python. The code IS the math.
"""

import math
import random
import sys

# ═══════════════════════════════════════════════════════════════
# §1  VECTOR OPERATIONS
# ═══════════════════════════════════════════════════════════════

def vzero(d):        return [0.0] * d
def vrand(d, s=1.0): return [random.gauss(0, s) for _ in range(d)]
def vadd(a, b):      return [ai+bi for ai,bi in zip(a,b)]
def vsub(a, b):      return [ai-bi for ai,bi in zip(a,b)]
def vscale(v, s):    return [vi*s for vi in v]
def vmul(a, b):      return [ai*bi for ai,bi in zip(a,b)]
def vdot(a, b):      return sum(ai*bi for ai,bi in zip(a,b))
def vnorm(v):        return math.sqrt(sum(vi*vi for vi in v) + 1e-15)
def vcosine(a, b):
    na, nb = vnorm(a), vnorm(b)
    if na < 1e-10 or nb < 1e-10: return 0.0
    return max(-1.0, min(1.0, vdot(a,b)/(na*nb)))


# ═══════════════════════════════════════════════════════════════
# §2  THE SELF-REFERENTIAL MAP
# ═══════════════════════════════════════════════════════════════

def phi(x, alpha, beta):
    """
    Φ(x)_k = tanh(α·x_k + β·x_{k+1}·x_{k-1})

    The state determines the dynamics through the product term.
    The product x_{k+1}·x_{k-1} gates dimension k based on its
    neighbors' values. This creates SPATIAL STRUCTURE within a
    single state vector — structure that was never programmed.

    α > 1: zero is unstable. The system MUST find non-trivial states.
    β > 0: cross-coupling creates correlations across dimensions.
    """
    d = len(x)
    out = [0.0] * d
    for k in range(d):
        kp = (k + 1) % d
        km = (k - 1) % d
        out[k] = math.tanh(alpha * x[k] + beta * x[kp] * x[km])
    return out


def phi_cross(x_self, x_other, alpha, beta):
    """
    Φ_self(other): cell applies its own structure to another's state.

    Φ_self(y)_k = tanh(α·y_k + β·x_self_{k+1} · y_{k-1})

    The 'program' (cross-coupling pattern) comes from x_self.
    The 'data' comes from x_other.
    """
    d = len(x_self)
    out = [0.0] * d
    for k in range(d):
        kp = (k + 1) % d
        km = (k - 1) % d
        out[k] = math.tanh(alpha * x_other[k] + beta * x_self[kp] * x_other[km])
    return out


def fixed_point_distance(x, alpha, beta):
    """‖Φ(x) - x‖ / max(‖x‖, 1). How far from self-consistency."""
    p = phi(x, alpha, beta)
    diff = vsub(p, x)
    return vnorm(diff) / max(vnorm(x), 1.0)


def trajectory_energy(history, window=5):
    """Average displacement over recent steps. Low = settled. High = active."""
    if len(history) < 2:
        return 0.0
    recent = history[-window:]
    total = 0.0
    for i in range(1, len(recent)):
        total += vnorm(vsub(recent[i], recent[i-1]))
    return total / (len(recent) - 1)


# ═══════════════════════════════════════════════════════════════
# §3  CELL: A SELF-SUSTAINING UNIT
# ═══════════════════════════════════════════════════════════════

class Cell:
    """
    A self-referential computational unit.

    State x ∈ ℝ^d IS the dynamics:
    - x determines Φ through the cross-coupling term
    - Φ determines the next x
    - The loop never opens

    The cell maintains a short trajectory history to measure
    its own dynamical character (settled vs active vs chaotic).
    """
    __slots__ = ('d', 'x', 'history', 'hist_len')

    def __init__(self, d, scale=0.5):
        self.d = d
        self.x = vrand(d, scale)
        self.hist_len = 12
        self.history = [self.x[:]]

    def record(self):
        self.history.append(self.x[:])
        if len(self.history) > self.hist_len:
            self.history.pop(0)

    def activity(self):
        """How dynamically active this cell is (recent trajectory energy)."""
        return trajectory_energy(self.history, min(8, len(self.history)))

    def fp_dist(self, alpha, beta):
        return fixed_point_distance(self.x, alpha, beta)

    def plasticity(self, alpha, beta, sigma=0.15):
        """
        High near fixed points (paradoxically: settled cells are RECEPTIVE).
        Low when far from any fixed point (active cells resist perturbation).

        This is the opposite of RK's autonomy. A cell that has found
        self-consistency is OPEN to the world. A cell in turmoil is closed.

        Why? Because a cell at a fixed point has spare capacity.
        A cell actively computing needs all its dynamics for itself.
        """
        d = self.fp_dist(alpha, beta)
        return math.exp(-(d * d) / (sigma * sigma))


# ═══════════════════════════════════════════════════════════════
# §4  THE ENGINE
# ═══════════════════════════════════════════════════════════════

class Engine:
    """
    N self-referential cells coupled through state-derived topology.

    Update for cell i:
      raw_i = Φ(x_i)                                    (self-application)
      pull_i = Σ_j a_ij · [Φ_i(x_j) − Φ(x_i)]         (coupling)
      x_i' = raw_i + p_i · ε · pull_i + signal          (integration)

    Where:
      p_i = plasticity (high at fixed points, low during activity)
      a_ij = softmax(x_i · x_j / dτ)  (state-similarity coupling)
      ε = coupling strength

    The mixing rate δ smooths the update:
      x_i(t+1) = (1−δ)·x_i(t) + δ·x_i'
    """

    def __init__(self, n=8, d=12, alpha=1.15, beta=0.5, seed=None):
        if seed is not None:
            random.seed(seed)
        self.n = n
        self.d = d
        self.alpha = alpha
        self.beta = beta
        self.cells = [Cell(d, scale=0.5) for _ in range(n)]
        self.epsilon = 0.3   # coupling strength
        self.tau = 0.4       # attention temperature
        self.delta = 0.4     # update smoothing
        self.noise = 0.005   # prevents stagnation
        self.t = 0
        self.history = []    # system-level trajectory

    def coupling_weights(self, i):
        """a_ij = softmax(x_i · x_j / (d·τ)), j ≠ i."""
        xi = self.cells[i].x
        n, d, tau = self.n, self.d, self.tau
        raw = []
        for j in range(n):
            if i == j:
                raw.append(-1e10)
            else:
                raw.append(vdot(xi, self.cells[j].x) / (d * tau))
        mx = max(raw)
        exps = [math.exp(min(r - mx, 50)) for r in raw]
        s = sum(exps) + 1e-15
        return [e / s for e in exps]

    def step(self, signal=None, signal_strength=0.3):
        """One integration step."""
        n, d = self.n, self.d
        alpha, beta = self.alpha, self.beta
        cells = self.cells

        new_states = []

        for i in range(n):
            ci = cells[i]

            # Self-application: the cell's own dynamics
            raw = phi(ci.x, alpha, beta)

            # Coupling: neighbors' programs applied to this cell
            pi = ci.plasticity(alpha, beta)
            if pi > 0.01 and self.epsilon > 0:
                weights = self.coupling_weights(i)
                pull = vzero(d)
                for j in range(n):
                    if i == j:
                        continue
                    w = weights[j]
                    if w < 1e-8:
                        continue
                    cross = phi_cross(cells[j].x, ci.x, alpha, beta)
                    diff = vsub(cross, raw)
                    pull = vadd(pull, vscale(diff, w))
                raw = vadd(raw, vscale(pull, pi * self.epsilon))

            # External signal: enters through plasticity gate
            if signal is not None:
                raw = vadd(raw, vscale(signal, pi * signal_strength))

            # Small noise to prevent perfect stagnation
            raw = vadd(raw, vrand(d, self.noise))

            # Smooth update
            new_x = vadd(vscale(ci.x, 1 - self.delta), vscale(raw, self.delta))
            new_states.append(new_x)

        # Apply all updates simultaneously
        for i in range(n):
            cells[i].x = new_states[i]
            cells[i].record()

        self.t += 1

    def inject(self, pattern, cell_indices=None):
        """Set cell states directly (for testing attractor basins)."""
        if cell_indices is None:
            cell_indices = range(self.n)
        for i in cell_indices:
            self.cells[i].x = pattern[:]
            self.cells[i].history = [pattern[:]]

    # ── Observables ──────────────────────────────────────────

    def mean_fp_dist(self):
        return sum(c.fp_dist(self.alpha, self.beta) for c in self.cells) / self.n

    def mean_activity(self):
        return sum(c.activity() for c in self.cells) / self.n

    def mean_plasticity(self):
        return sum(c.plasticity(self.alpha, self.beta) for c in self.cells) / self.n

    def mean_norm(self):
        return sum(vnorm(c.x) for c in self.cells) / self.n

    def centroid(self):
        """Mean state across all cells."""
        c = vzero(self.d)
        for cell in self.cells:
            c = vadd(c, vscale(cell.x, 1.0 / self.n))
        return c

    def dispersion(self):
        """How spread out are cell states."""
        c = self.centroid()
        return sum(vnorm(vsub(cell.x, c))**2 for cell in self.cells) / self.n

    def snapshot(self):
        return [c.x[:] for c in self.cells]

    def measure(self):
        return dict(
            t=self.t,
            fp=round(self.mean_fp_dist(), 4),
            act=round(self.mean_activity(), 5),
            pla=round(self.mean_plasticity(), 4),
            nrm=round(self.mean_norm(), 4),
            dis=round(self.dispersion(), 4))


# ═══════════════════════════════════════════════════════════════
# §5  EXPERIMENTS
# ═══════════════════════════════════════════════════════════════

def bar(v, w=20, lo=0.0, hi=1.0):
    f = max(0.0, min(1.0, (v - lo) / (hi - lo + 1e-10)))
    n = int(f * w)
    return '█' * n + '░' * (w - n)

def cosine(a, b):
    return vcosine(a, b)

W = 72

def header(title, subtitle=""):
    print(f"\n{'─' * W}")
    print(f"  {title}")
    if subtitle:
        print(f"  {subtitle}")
    print(f"{'─' * W}\n")

def run():
    print("=" * W)
    print("  SELF-SUSTAINING COMPUTATION")
    print()
    print("  Φ(x)_k = tanh(α·x_k + β·x_{k+1}·x_{k-1})")
    print("  State determines dynamics. Trajectory is computation.")
    print("=" * W)

    # ── §1: Does the system self-organize? ───────────────────

    header("§1  SELF-ORGANIZATION",
           "From random noise → structured dynamics. No loss function.")

    E = Engine(n=8, d=12, alpha=1.15, beta=0.5, seed=42)

    print(f"  {'step':>5}  {'fp_dist':>8}  {'activity':>9}  {'plastic':>8}"
          f"  {'‖x‖':>7}  {'disper':>7}  convergence")
    print(f"  {'─'*5}  {'─'*8}  {'─'*9}  {'─'*8}  {'─'*7}  {'─'*7}  {'─'*20}")

    for epoch in range(20):
        for _ in range(50):
            E.step()
        m = E.measure()
        print(f"  {m['t']:>5}  {m['fp']:>8.4f}  {m['act']:>9.5f}  {m['pla']:>8.4f}"
              f"  {m['nrm']:>7.3f}  {m['dis']:>7.4f}  {bar(1-m['fp'], 20)}")

    # Per-cell report
    header("§1b  PER-CELL STATE")
    print(f"  {'cell':>4}  {'fp_dist':>8}  {'activity':>9}  {'plastic':>8}"
          f"  {'‖x‖':>7}  character")
    for i, c in enumerate(E.cells):
        fp = c.fp_dist(E.alpha, E.beta)
        act = c.activity()
        pla = c.plasticity(E.alpha, E.beta)
        nrm = vnorm(c.x)
        if fp < 0.05:
            char = "FIXED POINT"
        elif fp < 0.15 and act < 0.01:
            char = "near-fixed"
        elif act > 0.05:
            char = "ACTIVE"
        else:
            char = "settling"
        print(f"  {i:>4}  {fp:>8.4f}  {act:>9.5f}  {pla:>8.4f}"
              f"  {nrm:>7.3f}  {char}")

    so_fp = E.mean_fp_dist()
    so_nrm = E.mean_norm()

    # ── §2: Perturbation and homeostasis ─────────────────────

    header("§2  PERTURBATION & HOMEOSTASIS",
           "Structured signal injected. Does the system absorb and recover?")

    pre = E.measure()
    pre_snap = E.snapshot()

    sig = vzero(12)
    sig[0] = 2.0; sig[1] = -1.5; sig[4] = 1.0; sig[7] = -1.0

    print(f"  {'phase':<12} {'step':>5}  {'fp_dist':>8}  {'activity':>9}  {'‖x‖':>7}")
    print(f"  {'─'*12} {'─'*5}  {'─'*8}  {'─'*9}  {'─'*7}")

    for ep in range(6):
        for _ in range(30):
            E.step(signal=sig)
        m = E.measure()
        print(f"  {'PERTURBED':<12} {m['t']:>5}  {m['fp']:>8.4f}  {m['act']:>9.5f}  {m['nrm']:>7.3f}")

    print()
    for ep in range(8):
        for _ in range(30):
            E.step()
        m = E.measure()
        print(f"  {'recovering':<12} {m['t']:>5}  {m['fp']:>8.4f}  {m['act']:>9.5f}  {m['nrm']:>7.3f}")

    post = E.measure()
    post_snap = E.snapshot()

    # Measure recovery: how similar are pre/post states?
    recovery_sims = [cosine(pre_snap[i], post_snap[i]) for i in range(E.n)]
    avg_recovery = sum(recovery_sims) / len(recovery_sims)
    delta_fp = abs(post['fp'] - pre['fp'])

    if delta_fp < 0.05 and avg_recovery > 0.8:
        verdict = "HOMEOSTASIS"
    elif avg_recovery > 0.5:
        verdict = "PARTIAL RECOVERY"
    else:
        verdict = "REORGANIZED"
    print(f"\n  → {verdict}: Δfp_dist={delta_fp:.4f}, avg state recovery={avg_recovery:.4f}")

    # ── §3: Attractor basin classification ───────────────────

    header("§3  ATTRACTOR BASIN CLASSIFICATION",
           "Different inputs → different attractors? Same class → same attractor?")

    def make_pattern(seed_vals, d=12, noise=0.0):
        """Create a d-dimensional pattern from seed values, with optional noise."""
        random.seed(None)  # use current random state for noise
        p = [0.0] * d
        for k, v in seed_vals.items():
            if k < d:
                p[k] = v
        if noise > 0:
            p = [pk + random.gauss(0, noise) for pk in p]
        return p

    # Three pattern classes
    class_A = {0: 0.8, 1: 0.8, 2: 0.8, 3: -0.5, 4: -0.5}     # "warm front"
    class_B = {0: -0.5, 1: -0.5, 6: 0.8, 7: 0.8, 8: 0.8}      # "cold front"
    class_C = {3: 0.6, 4: 0.6, 5: 0.6, 9: 0.6, 10: 0.6}       # "middle band"

    def classify(pattern, n_settle=200):
        """Inject pattern into fresh engine, settle, return centroid."""
        eng = Engine(n=6, d=12, alpha=1.15, beta=0.5, seed=7)
        eng.inject(pattern)
        for _ in range(n_settle):
            eng.step()
        return eng.centroid()

    print("  Running classification trials...\n")

    n_trials = 5
    results = {}
    for label, template in [("A", class_A), ("B", class_B), ("C", class_C)]:
        centroids = []
        for trial in range(n_trials):
            p = make_pattern(template, noise=0.15)
            c = classify(p)
            centroids.append(c)
        results[label] = centroids

    # Within-class similarity (should be HIGH)
    print("  Within-class consistency (cosine similarity of final centroids):")
    within = {}
    for label, cents in results.items():
        sims = []
        for i in range(len(cents)):
            for j in range(i+1, len(cents)):
                sims.append(cosine(cents[i], cents[j]))
        avg = sum(sims) / len(sims) if sims else 0
        within[label] = avg
        print(f"    Class {label}: {avg:+.4f}  {bar(avg, 15, -1, 1)}")

    # Between-class similarity (should be LOW)
    print("\n  Between-class discrimination:")
    between = {}
    for l1 in results:
        for l2 in results:
            if l1 >= l2:
                continue
            sims = []
            for c1 in results[l1]:
                for c2 in results[l2]:
                    sims.append(cosine(c1, c2))
            avg = sum(sims) / len(sims)
            between[(l1,l2)] = avg
            print(f"    {l1} vs {l2}: {avg:+.4f}  {bar(avg, 15, -1, 1)}")

    # Is within > between?
    min_within = min(within.values())
    max_between = max(abs(v) for v in between.values())
    classifies = min_within > max_between + 0.1

    print(f"\n  Min within-class: {min_within:+.4f}")
    print(f"  Max |between-class|: {max_between:+.4f}")
    print(f"  → {'CLASSIFIES — attractor basins discriminate inputs'if classifies else 'Insufficient separation (needs tuning or more dimensions)'}")

    # ── §4: History-dependent computation ────────────────────

    header("§4  HISTORY-DEPENDENT COMPUTATION",
           "Same initial conditions + different conditioning → different responses.")

    def conditioned_engine(cond_signal, n_self=300, n_cond=200, n_settle=200):
        eng = Engine(n=6, d=12, alpha=1.15, beta=0.5, seed=100)
        for _ in range(n_self):
            eng.step()
        for _ in range(n_cond):
            eng.step(signal=cond_signal, signal_strength=0.5)
        for _ in range(n_settle):
            eng.step()
        return eng

    cond_A = vzero(12)
    cond_A[0] = 1.5; cond_A[1] = 1.5; cond_A[2] = 1.0
    cond_B = vzero(12)
    cond_B[6] = 1.5; cond_B[7] = 1.5; cond_B[8] = 1.0

    print("  Conditioning A: excite dimensions {0,1,2}")
    eA = conditioned_engine(cond_A)
    print(f"    fp_dist={eA.mean_fp_dist():.4f}  ‖x‖={eA.mean_norm():.4f}")

    print("  Conditioning B: excite dimensions {6,7,8}")
    eB = conditioned_engine(cond_B)
    print(f"    fp_dist={eB.mean_fp_dist():.4f}  ‖x‖={eB.mean_norm():.4f}")

    # Compare states
    cA = eA.centroid()
    cB = eB.centroid()
    state_sim = cosine(cA, cB)
    state_div = vnorm(vsub(cA, cB))

    print(f"\n  Post-conditioning state comparison:")
    print(f"    Centroid cosine:     {state_sim:+.4f}")
    print(f"    Centroid divergence: {state_div:.4f}")

    # Same test input
    random.seed(555)
    test = vrand(12, 0.8)

    # Measure response: inject test, run, measure displacement
    def response(eng, test_signal, steps=100):
        before = eng.centroid()
        for _ in range(steps):
            eng.step(signal=test_signal, signal_strength=0.3)
        after = eng.centroid()
        return vsub(after, before)

    rA = response(Engine(n=6, d=12, alpha=1.15, beta=0.5, seed=100), test)  # unconditioned
    # Need to re-create conditioned engines (response mutates them)
    eA2 = conditioned_engine(cond_A)
    eB2 = conditioned_engine(cond_B)
    rA_cond = response(eA2, test)
    rB_cond = response(eB2, test)

    cos_AB = cosine(rA_cond, rB_cond)
    cos_Abase = cosine(rA, rA_cond)
    cos_Bbase = cosine(rA, rB_cond)

    print(f"\n  Same test signal applied to conditioned systems:")
    print(f"    ‖response_A‖ = {vnorm(rA_cond):.4f}")
    print(f"    ‖response_B‖ = {vnorm(rB_cond):.4f}")
    print(f"    cos(resp_A, resp_B) = {cos_AB:+.4f}")

    history_ok = abs(cos_AB) < 0.85 or abs(state_sim) < 0.85
    print(f"\n  → {'HISTORY SHAPES COMPUTATION' if history_ok else 'Conditioning had minimal effect'}")

    # ── §5: Fixed-point landscape ────────────────────────────

    header("§5  FIXED-POINT LANDSCAPE",
           "What attractors exist for isolated cells under pure Φ?")

    random.seed(0)
    fp_found = []
    N_trials = 60

    for trial in range(N_trials):
        x = vrand(12, 0.7)
        for _ in range(2000):
            p = phi(x, 1.15, 0.5)
            x = vadd(vscale(x, 0.6), vscale(p, 0.4))
            x = vadd(x, vrand(12, 0.003))
            # Soft norm constraint
            n = vnorm(x)
            if n > 3.0:
                x = vscale(x, 3.0 / n)
        d = fixed_point_distance(x, 1.15, 0.5)
        if d < 0.05:
            fp_found.append((d, vnorm(x), x))

    print(f"  {len(fp_found)}/{N_trials} converged to fixed point (d < 0.05)\n")

    if len(fp_found) >= 2:
        # Pairwise diversity
        cos_pairs = []
        for i in range(min(len(fp_found), 15)):
            for j in range(i+1, min(len(fp_found), 15)):
                cos_pairs.append(abs(cosine(fp_found[i][2], fp_found[j][2])))
        avg_cos = sum(cos_pairs) / len(cos_pairs) if cos_pairs else 1.0

        norms = [f[1] for f in fp_found]
        norm_var = sum((n - sum(norms)/len(norms))**2 for n in norms) / len(norms)

        print(f"  {'fp_dist':>8}  {'‖x‖':>7}")
        print(f"  {'─'*8}  {'─'*7}")
        for d, nrm, _ in sorted(fp_found)[:12]:
            print(f"  {d:>8.4f}  {nrm:>7.3f}")

        print(f"\n  Avg |cosine| between fixed points: {avg_cos:.4f}")
        print(f"  Norm variance: {norm_var:.4f}")
        diversity_ok = avg_cos < 0.7
        print(f"  → {'DIVERSE landscape' if diversity_ok else 'Limited diversity'}")
    else:
        diversity_ok = False
        avg_cos = 1.0
        print("  Too few fixed points found for diversity analysis.")

    # ── §6: Computational capacity ───────────────────────────

    header("§6  COMPUTATIONAL CAPACITY",
           "Can the system distinguish structured inputs from noise?")

    def signal_response_profile(eng_seed, signal, steps=80):
        """Fresh engine → inject signal → measure trajectory character."""
        eng = Engine(n=6, d=12, alpha=1.15, beta=0.5, seed=eng_seed)
        for _ in range(200):
            eng.step()  # self-organize

        pre_centroid = eng.centroid()
        pre_disp = eng.dispersion()

        for _ in range(steps):
            eng.step(signal=signal, signal_strength=0.4)

        post_centroid = eng.centroid()
        post_disp = eng.dispersion()

        return {
            'displacement': vnorm(vsub(post_centroid, pre_centroid)),
            'disp_change': post_disp - pre_disp,
            'final_fp': eng.mean_fp_dist(),
            'final_centroid': post_centroid
        }

    # Structured signals vs noise
    random.seed(42)
    structured = [
        ("low_freq",  [math.sin(2*math.pi*k/12) * 0.8 for k in range(12)]),
        ("high_freq", [math.sin(2*math.pi*k/3) * 0.8 for k in range(12)]),
        ("step",      [0.8]*6 + [-0.8]*6),
        ("impulse",   [2.0] + [0.0]*11),
    ]
    noise_signals = [("noise_"+str(i), vrand(12, 0.8)) for i in range(4)]

    print(f"  {'signal':<12} {'displace':>9}  {'Δdisper':>9}  {'fp_dist':>8}")
    print(f"  {'─'*12} {'─'*9}  {'─'*9}  {'─'*8}")

    struct_displacements = []
    noise_displacements = []

    for label, sig in structured:
        r = signal_response_profile(77, sig)
        struct_displacements.append(r['displacement'])
        print(f"  {label:<12} {r['displacement']:>9.4f}  {r['disp_change']:>+9.4f}  {r['final_fp']:>8.4f}")

    print()
    for label, sig in noise_signals:
        r = signal_response_profile(77, sig)
        noise_displacements.append(r['displacement'])
        print(f"  {label:<12} {r['displacement']:>9.4f}  {r['disp_change']:>+9.4f}  {r['final_fp']:>8.4f}")

    # Does the system respond differently to structure vs noise?
    avg_struct = sum(struct_displacements) / len(struct_displacements)
    avg_noise = sum(noise_displacements) / len(noise_displacements)

    # Check if structured signals produce more VARIED responses
    struct_var = sum((d - avg_struct)**2 for d in struct_displacements) / len(struct_displacements)
    noise_var = sum((d - avg_noise)**2 for d in noise_displacements) / len(noise_displacements)

    print(f"\n  Structured: mean disp={avg_struct:.4f}, variance={struct_var:.6f}")
    print(f"  Noise:      mean disp={avg_noise:.4f}, variance={noise_var:.6f}")

    discriminates = struct_var > noise_var * 1.5 or abs(avg_struct - avg_noise) > 0.05
    print(f"  → {'DISCRIMINATES structure from noise' if discriminates else 'Response insensitive to structure'}")

    # ── §7: Self-reference verification ──────────────────────

    header("§7  SELF-REFERENCE VERIFICATION",
           "Is the system actually self-referential? Ablation test.")

    print("  Comparing: full dynamics vs ablated (β=0, no self-reference)\n")

    eng_full = Engine(n=6, d=12, alpha=1.15, beta=0.5, seed=50)
    eng_ablated = Engine(n=6, d=12, alpha=1.15, beta=0.0, seed=50)

    print(f"  {'step':>5}  {'full_fp':>8}  {'abl_fp':>8}  {'full_‖x‖':>8}  {'abl_‖x‖':>8}  {'full_dis':>8}  {'abl_dis':>8}")
    print(f"  {'─'*5}  {'─'*8}  {'─'*8}  {'─'*8}  {'─'*8}  {'─'*8}  {'─'*8}")

    for epoch in range(10):
        for _ in range(60):
            eng_full.step()
            eng_ablated.step()
        mf = eng_full.measure()
        ma = eng_ablated.measure()
        print(f"  {mf['t']:>5}  {mf['fp']:>8.4f}  {ma['fp']:>8.4f}"
              f"  {mf['nrm']:>8.4f}  {ma['nrm']:>8.4f}"
              f"  {mf['dis']:>8.4f}  {ma['dis']:>8.4f}")

    # The ablated system (β=0) should be qualitatively different
    mf_final = eng_full.measure()
    ma_final = eng_ablated.measure()

    # Check if structures differ
    full_disper = mf_final['dis']
    abl_disper = ma_final['dis']
    ablation_diff = abs(full_disper - abl_disper) / max(full_disper, abl_disper, 0.001)

    print(f"\n  Full system dispersion:   {full_disper:.4f}")
    print(f"  Ablated system dispersion: {abl_disper:.4f}")
    print(f"  Relative difference:       {ablation_diff:.4f}")
    sr_matters = ablation_diff > 0.1 or abs(mf_final['fp'] - ma_final['fp']) > 0.05
    print(f"  → {'SELF-REFERENCE MATTERS — β creates qualitatively different dynamics' if sr_matters else 'Minimal effect (β too weak or system in wrong regime)'}")

    # ═══════════════════════════════════════════════════════════
    # SUMMARY
    # ═══════════════════════════════════════════════════════════

    print(f"\n{'═' * W}")
    print("  RESULTS")
    print(f"{'═' * W}\n")

    convergence_ok = so_fp < 0.15
    homeostasis_ok = delta_fp < 0.05 and avg_recovery > 0.7
    diversity_ok_final = len(fp_found) > N_trials * 0.2 and (avg_cos < 0.7 if len(fp_found) >= 2 else False)

    checks = [
        ("Self-organization (fp_dist < 0.15)",    convergence_ok,   f"{so_fp:.4f}"),
        ("Homeostasis after perturbation",        homeostasis_ok,   f"Δ={delta_fp:.4f}, rec={avg_recovery:.3f}"),
        ("Attractor basin classification",        classifies,       f"within>{min_within:.2f} between<{max_between:.2f}"),
        ("History-dependent computation",         history_ok,       f"state_cos={state_sim:+.3f}"),
        ("Fixed-point diversity",                 diversity_ok_final, f"{len(fp_found)}/{N_trials} found"),
        ("Structure discrimination",              discriminates,    f"struct_var={struct_var:.4f}"),
        ("Self-reference matters (ablation)",     sr_matters,       f"diff={ablation_diff:.3f}"),
    ]

    for name, ok, detail in checks:
        sym = "■" if ok else "□"
        print(f"  {sym} {name:<42} {detail}")

    n_pass = sum(1 for _, ok, _ in checks if ok)
    print(f"\n  {n_pass}/7 criteria met.")

    print(f"""
{'─' * W}

  WHAT THIS IS:

  A system where each cell's state vector determines — through the
  cross-coupling term β·x_{{k+1}}·x_{{k-1}} — exactly how that cell
  transforms signals. The state IS the program. The program IS the
  state. When Φ(x) ≈ x, the cell has found a state that reproduces
  itself through its own dynamics. When Φ(x) ≠ x, the cell is still
  searching, still computing, still alive.

  The cross-coupling creates SPATIAL STRUCTURE within a single state
  vector. Dimension k is gated by the product of its neighbors.
  This product term is what makes the dynamics self-referential:
  the state literally multiplies itself to determine its own update.

  WHAT THIS IS NOT:

  This is not a neural network. It has no training, no loss function,
  no gradient descent. It does not compete with GPT on benchmarks.

  It is a proof of concept: self-referential dynamics can produce
  self-organization, homeostasis, attractor-based classification,
  and history-dependent computation — without any external objective.

  WHAT IT CHALLENGES:

  Current architectures scale by adding parameters.
  This system's computational capacity comes from its DYNAMICS —
  the number and structure of attractor basins, which grow with
  interaction time, not parameter count.

  The open question: can this principle be scaled to useful
  computation? That requires showing universality (any function
  can be computed through attractor dynamics) and efficiency
  (the time-for-space trade is favorable).

  These are hard problems. This code is the starting point.

{'─' * W}
""")


if __name__ == '__main__':
    run()
